### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by kousu** [anthonywong/rtl8723bs#9]
What's the relationship between this project and https://github.com/hadess/rtl8723bs? @hadess's copy has apparently been merged into kernel 4.12 and [emptied](https://github.com/hadess/rtl8723bs/commit/3bb1d33ad98c1d77b5e17a1b707e137b35e6d0a5) as a result, but we're only up to kernel 4.11 so far so the driver is [only in staging so far](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/staging/rtl8723bs).  Until 4.12, I want to know what codebase I should be using; currently I'm using @muhviehstah's [copy](https://github.com/muhviehstah/rtl8723bs) (with minor build patches documented, perhaps uselessly I see now, at #7 and #8) and it is working (on ArchLinux), but I would like to know if someday soon I'll need to uninstall it or if I should go build @hadess's [latest copy](https://github.com/hadess/rtl8723bs/tree/db2c4f61d48fe3b47c167c8bcd722ce83c24aca5) or maybe go get the (same?) code manually [out of the linux tree](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/staging/rtl8723bs)

Also, do you know what is the relationship of these repostitories to [rltwifi](https://github.com/lwfinger/rtlwifi_new)? rtlwifi supports a bunch of models including rtl8723ae and rtl8723be, but not, apparently, rtl8723bs; is that correct? Do you know if rtlwifi is getting merged into the kernel or is it going to remain an external codebase forever?

@anthonywong and @muhviehstah, would you update your README to include a warning if you're not anymore the latest source code? Especially @muhviehstah, since your fork is [linked from the AUR](https://aur.archlinux.org/packages/8723bs-git-dkms/).

Thank you for all your hard work everyone, getting this obscure chipset working.

**Comment by muhviehstah** [comment]
you should use hadess version, its good that it is merged into the kernel tree.

in the past i had some issues with the version of hadess, so i forked anthony's version and tried to fix issues with newer kernel versions

I have created 2 aur packages. r8723bs-git  (hadess) & 8723bs-git (anthony). r8723bs-git will be obsolte now. 

i have updated the pkgdesc of 8723bs-git with a warning and i will fix the build with newer kernels as soon i have some time. (pull requests are welcome)

**Comment by kousu** [comment]
I just `pacman -Syu`'d and got kernel 4.12, which at first gave me no wifi at all until I `pacman -R 8723-git-dkms`, and which now gives me

```
# dmesg
...
r8723bs: module is from the staging directory, the quality is unknown, you have been warned.
RTL8723BS: rtl8723bs v4.3.5.5_12290.20140916_BTCOEX20140507-4E40
RTL8723BS: rtl8723bs BT-Coex version = BTCOEX20140507-4E40
...
```

So good work getting this ready for upstream! I guess hadess's fork might still be useful for, say, Debian-stable people, but I am happy.

Thank you for the update on the details 👍

**Comment by muhviehstah** [comment]
ok maybe i should add kernel 4.12+ to "conflicts" in the PKGBUILD

thanks for the info
